name: Cancel Previous Workflow Runs
on:
  workflow_run:
    workflows: ["Dynamic analysis", "Docker Container tests", "Static analysis"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          workflow_id: ${{ github.event.workflow.id }}